---
title: "Metabolism of A Noodle Restaurant about Food Loss and Food Waste:
Micro-Level Material Flow Model and Tobit Regression Analysis"
---

# Library
```{r Library, include=FALSE}
# Library ----------------------------------------------------------------------
library(ggplot2) # ggplot
library(lubridate) # wday function
library(gridExtra) # grid.arrange function
library(ggcorrplot) # cor_pmat
library(forecast) # ggAcf
library(tseries) # adf.test
library(performance) # check_model
library(see) # check_model
library(dplyr) # mutate
library(tidyverse)


# Source -----------------------------------------------------------------------
source("isValidSheet.R",  encoding="utf-8")
source("dataGetFrom.R",   encoding="utf-8")
source("prepNetWeight.R", encoding="utf-8")
source("prepWeek.R",      encoding="utf-8")
source("prepInputs.R",    encoding="utf-8")
```

# Data Retrieve
```{r data_import}
URL = "https://docs.google.com/spreadsheets/d/1QDdgc_fR1_iALRschw7ymXOE7EJmEqAP_Xp_b6mwHP4/edit?usp=sharing"
sheet.raw <- dataGetFrom(URL)
# View(sheet.raw)
```

## data check
```{r data_check}
# Check list -------------------------------------------------------------------
# Check for sheet existence and data frame format
# Check if isClosed is 0 or 1
# Check for Date
# Check for to-go container column (0 and 1)
# Check for negative values for measurements or observations
# Check if weather conditions (temperature) is between -50 to 50
# Check if weather conditions (humiditiy) is between 0 to 100
# Check if precipitation has negative value

isValidSheet(sheet.raw)
```



# Data Preprocess
## Convert Gross weight to Net weight of FLW
```{r gross_to_net_weight}
rm(sheet.net)
sheet.net <- prepNetWeight(sheet.raw)
sheets <- merge(sheet.raw, sheet.net, by = "date")
```

## Append day of the week as Dummy and Effect variable
```{r day of the week}
# based day of the week must be either Tue, Wed, Thu, Fri, Sat, Sun.
sheet.week <- prepWeek(sheet.net, "Sun")
# View(sheet.week)
# rm(df)
# sheets <- merge(sheets, sheet.week, by = "date")
```

## Daily mass balance model in the restaurant
```{r food_inputs_estimate}
numComp = 13
AdjMat <- matrix(c(0,0,0,-0.15,    # 1. noodle
                  -0.46,0,0,-0.19, # 2. water
                  -0.165,0,0,0,    # 3. bones
                  -0.094,0,0,0,    # 4. vegetables
                  -0.04,0,0,0,     # 5. meat
                  -0.015,0,0,0,    # 6. condiments
                  0.56,-0.56,0,0,  # 7. Broth
                  0,0.56,0,0,      # 8. Stock
                  0,0,0.214,0,     # 9. Food Loss
                  0,0,-0.165,0,    # 10.bones of Food Loss
                  0,0,-0.044,0,    # 11.vegs of Food Loss
                  0,0,-0.005,0,    # 12.meat of Food Loss
                  0,0,0,0.9),      # 13.Final Product
                ncol=numComp)

daily_total_served <- AdjMat[4,13]*(sheet.raw$ramen_orders+
                                    sheet.raw$takeouts +sheet.raw$mini_orders/2)
daily_food_loss <- sheet.net$food_loss_kg
rm(sheet.inputs)
sheet.inputs <- prepInputs(sheet.raw,AdjMat,
                           daily_total_served, AdjMat[4,13],
                           daily_food_loss, AdjMat[3,9])
sheets <- merge(sheets, sheet.inputs, by = "date")
```

```{r rename data variables}
df <- data.frame(
  date      = as.Date(sheets$date),        # date
  day       = as.character(sheets$day.x),  # day of the week
  is_closed = as.logical(sheets$isClosed), # the restaurant closed or not
  # food loss and waste vars
  food_loss_kg    = sheets$food_loss_kg,   #
  food_waste_kg   = sheets$food_waste_kg,  #
  solid_waste_kg  = sheets$solid_waste_kg, #
  liquid_waste_kg = sheets$liquid_waste_kg,#
  #business vars
  customers = sheets$customers,    #
  fulls     = sheets$ramen_orders, #
  halfs     = sheets$mini_orders,  #
  takeouts  = sheets$takeouts,     #
  liquors   = sheets$liquors,      #
  sales     = sheets$salesD,       #
  container = sheets$container,    #
  # weather conditions,
  temp_c  = sheets$avg_hourly_temperature,      #
  humi_p  = sheets$avg_hourly_relative_humidity,#
  prcp_mm = sheets$precipitation,               #
  # food inputs based on daily total served in kg
  TS_noodle_kg = sheets$totServ_input.1,
  TS_water_kg  = sheets$totServ_input.2,
  TS_bones_kg  = sheets$totServ_input.3,
  TS_veg_kg    = sheets$totServ_input.4,
  TS_meat_kg   = sheets$totServ_input.5,
  TS_condi_kg  = sheets$totServ_input.6,
  TS_Broth_kg  = sheets$totServ_input.7,
  TS_Stock_kg  = sheets$totServ_input.8,
  TS_FL_kg     = sheets$totServ_input.9,
  TS_FL_bone_kg = sheets$totServ_input.10,
  TS_FL_veg_kg  = sheets$totServ_input.11,
  TS_FL_meat_kg = sheets$totServ_input.12,
  TS_FP_kg     = sheets$totServ_input.13,
  # food inputs based on daily food loss in kg
  FL_noodle_kg = sheets$foodLoss_input.1,
  FL_water_kg  = sheets$foodLoss_input.2,
  FL_bones_kg  = sheets$foodLoss_input.3,
  FL_veg_kg    = sheets$foodLoss_input.4,
  FL_meat_kg   = sheets$foodLoss_input.5,
  FL_condi_kg  = sheets$foodLoss_input.6,
  FL_Broth_kg  = sheets$foodLoss_input.7,
  FL_Stock_kg  = sheets$foodLoss_input.8,
  FL_FL_kg     = sheets$foodLoss_input.9,
  FL_FL_bone_kg = sheets$foodLoss_input.10,
  FL_FL_veg_kg  = sheets$foodLoss_input.11,
  FL_FL_meat_kg = sheets$foodLoss_input.12,
  FL_FP_kg     = sheets$foodLoss_input.13,
  # 
  Broth_diff      = sheets$Broth_diff,
  Final_Prod_diff = sheets$Final_Prod_diff,
  daily_total_served = daily_total_served
)

sheet.week$date <- as.Date(sheet.week$date)
df <- merge(df, sheet.week[,c(-2)], by = "date")
```

```{r clean up sheets variables}
# delete sheets
rm(sheet.inputs);rm(sheet.net);rm(sheet.raw);rm(sheet.week);rm(sheets)
rm(daily_food_loss);rm(daily_total_served);rm(numComp);rm(URL);rm(loc)
rm(dataGetFrom);rm(isValidSheet);rm(prepInputs);rm(prepNetWeight);rm(prepWeek)
head(df)
```

